/** @format */

import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

export async function getServerSideProps() {
  const res = await fetch("https://jsonplaceholder.typicode.com/users");
  const data = await res.json();
  return {
    props: {
      users: data,
    },
  };
}
export default function Home({ users }) {
  if (!users) {
    return <h1>Loading...</h1>;
  } else {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <ul>
          {users.map((item) => {
            const { id, name, username, email } = item;
            return (
              <li key={id}>
                <Link href={`/userinfo/${id}`}>{name}</Link>
                <p>{username}</p>
                <h4>{email}</h4>
              </li>
            );
          })}
        </ul>
      </div>
    );
  }
}
